export enum ErrorCode {
  CONNECTION_FAILED = 'CONNECTION_FAILED',
  CONNECTION_LOST = 'CONNECTION_LOST',
  RECONNECT_EXHAUSTED = 'RECONNECT_EXHAUSTED',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',

  ERROR_MISSING_PARAMETERS = 'ERROR_MISSING_PARAMETERS',
  ERROR_INVALID_SYNTAX = 'ERROR_INVALID_SYNTAX',
  ERROR_UNSUPPORTED_NAMESPACE = 'ERROR_UNSUPPORTED_NAMESPACE',
  ERROR_UNSUPPORTED_COMMAND = 'ERROR_UNSUPPORTED_COMMAND',
  ERROR_INVALID_OBJECT_ID = 'ERROR_INVALID_OBJECT_ID',
  ERROR_INVALID_PARAMETER = 'ERROR_INVALID_PARAMETER',
  ERROR_COMMAND_FAILED = 'ERROR_COMMAND_FAILED',
  ERROR_NOT_CAPABLE = 'ERROR_NOT_CAPABLE',
  ERROR_NO_CONTENT = 'ERROR_NO_CONTENT',
}
